
```{r}
library("Sim.DiffProc")
set.seed(1000)
alfa=0.16
beta=0.08
t<-1
nu_pr<-10 #number of prices
initial_price<-runif(nu_pr,9,11)
alfa_est<-c()
beta_est<-c()
last_value<-c()
for (i in 1:nu_pr) {

traj <- GBM(N=365, M=1,t0=0, T=t, x0=initial_price[i], theta=alfa, sigma=beta)
# fit the parameters
fx <- expression( theta[1]*x ) ## drift coefficient of model (theta1 = theta)
gx <- expression( theta[2]*x ) ## diffusion coefficient of model (theta2 = sigma)
fit <- fitsde(data = traj, drift = fx, diffusion = gx, 
              start = list(theta1=0.15, theta2=0.1), 
              lower = c(0, 0), control = list(maxit=1000))
est<-coef(fit) ## estimates
alfa_est<-c(alfa_est,est[[1]])
beta_est<-c(beta_est,est[[2]])
last_value<-c(last_value, traj[365,])
                      }
alfa_est<-mean(alfa_est)
beta_est<-mean(beta_est)

print("Population parameters: alfa and beta")
alfa
beta
print("Estimates for parameters: alfa and beta")
alfa_est
beta_est
print("Population parameters: mean and variance")
mi<-exp(alfa*t)
sigma_sq<-exp(2*alfa*t)*(exp(beta^2*t)-1)
mi
sigma_sq
print("Estimates for population parameters: mean and variance")
mi_est<-exp(alfa_est*t)
sigma_sq_est<-exp(2*alfa_est*t)*(exp(beta_est^2*t)-1)
mi_est
sigma_sq_est
print("Sample elementary indices: Dutot, Carli, Jevons and their biases")
p0<-initial_price
p1<-last_value
N<-length(p0)
dutot<-sum(p1)/sum(p0)
carli<-mean(p1/p0)
jevons<-prod((p1/p0)^(1/N))
dutot
dutot-mi
carli
carli-mi
jevons
jevons-mi
print("Parametric sample elementary indices: Dutot=Carli, Jevons and P^J and their biases")
vol<-exp((1-N)*beta_est^2*t/(2*N^2))
exp(alfa_est*t)
exp(alfa_est*t)-mi
vol*exp(alfa_est*t)
vol*exp(alfa_est*t)-mi
exp((alfa_est-beta_est^2/2)*t)
exp((alfa_est-beta_est^2/2)*t)-mi


```

```{r}
library("Sim.DiffProc")
set.seed(1000)
alfa=0.16
beta=0.08
t<-1
nu_pr<-100 #number of prices
initial_price<-runif(nu_pr,9,11)
alfa_est<-c()
beta_est<-c()
last_value<-c()
for (i in 1:nu_pr) {

traj <- GBM(N=365, M=1,t0=0, T=t, x0=initial_price[i], theta=alfa, sigma=beta)
# fit the parameters
fx <- expression( theta[1]*x ) ## drift coefficient of model (theta1 = theta)
gx <- expression( theta[2]*x ) ## diffusion coefficient of model (theta2 = sigma)
fit <- fitsde(data = traj, drift = fx, diffusion = gx, 
              start = list(theta1=0.15, theta2=0.1), 
              lower = c(0, 0), control = list(maxit=1000))
est<-coef(fit) ## estimates
alfa_est<-c(alfa_est,est[[1]])
beta_est<-c(beta_est,est[[2]])
last_value<-c(last_value, traj[365,])
                      }
alfa_est<-mean(alfa_est)
beta_est<-mean(beta_est)

print("Population parameters: alfa and beta")
alfa
beta
print("Estimates for parameters: alfa and beta")
alfa_est
beta_est
print("Population parameters: mean and variance")
mi<-exp(alfa*t)
sigma_sq<-exp(2*alfa*t)*(exp(beta^2*t)-1)
mi
sigma_sq
print("Estimates for population parameters: mean and variance")
mi_est<-exp(alfa_est*t)
sigma_sq_est<-exp(2*alfa_est*t)*(exp(beta_est^2*t)-1)
mi_est
sigma_sq_est
print("Sample elementary indices: Dutot, Carli, Jevons and their biases")
p0<-initial_price
p1<-last_value
N<-length(p0)
dutot<-sum(p1)/sum(p0)
carli<-mean(p1/p0)
jevons<-prod((p1/p0)^(1/N))
dutot
dutot-mi
carli
carli-mi
jevons
jevons-mi
print("Parametric sample elementary indices: Dutot=Carli, Jevons and P^J and their biases")
vol<-exp((1-N)*beta_est^2*t/(2*N^2))
exp(alfa_est*t)
exp(alfa_est*t)-mi
vol*exp(alfa_est*t)
vol*exp(alfa_est*t)-mi
exp((alfa_est-beta_est^2/2)*t)
exp((alfa_est-beta_est^2/2)*t)-mi

```

```{r}
library("Sim.DiffProc")
set.seed(1000)
alfa=0.16
beta=0.08
t<-1
nu_pr<-1000 #number of prices
initial_price<-runif(nu_pr,9,11)
alfa_est<-c()
beta_est<-c()
last_value<-c()
for (i in 1:nu_pr) {

traj <- GBM(N=365, M=1,t0=0, T=t, x0=initial_price[i], theta=alfa, sigma=beta)
# fit the parameters
fx <- expression( theta[1]*x ) ## drift coefficient of model (theta1 = theta)
gx <- expression( theta[2]*x ) ## diffusion coefficient of model (theta2 = sigma)
fit <- fitsde(data = traj, drift = fx, diffusion = gx, 
              start = list(theta1=0.15, theta2=0.1), 
              lower = c(0, 0), control = list(maxit=1000))
est<-coef(fit) ## estimates
alfa_est<-c(alfa_est,est[[1]])
beta_est<-c(beta_est,est[[2]])
last_value<-c(last_value, traj[365,])
                      }
alfa_est<-mean(alfa_est)
beta_est<-mean(beta_est)

print("Population parameters: alfa and beta")
alfa
beta
print("Estimates for parameters: alfa and beta")
alfa_est
beta_est
print("Population parameters: mean and variance")
mi<-exp(alfa*t)
sigma_sq<-exp(2*alfa*t)*(exp(beta^2*t)-1)
mi
sigma_sq
print("Estimates for population parameters: mean and variance")
mi_est<-exp(alfa_est*t)
sigma_sq_est<-exp(2*alfa_est*t)*(exp(beta_est^2*t)-1)
mi_est
sigma_sq_est
print("Sample elementary indices: Dutot, Carli, Jevons and their biases")
p0<-initial_price
p1<-last_value
N<-length(p0)
dutot<-sum(p1)/sum(p0)
carli<-mean(p1/p0)
jevons<-prod((p1/p0)^(1/N))
dutot
dutot-mi
carli
carli-mi
jevons
jevons-mi
print("Parametric sample elementary indices: Dutot=Carli, Jevons and P^J and their biases")
vol<-exp((1-N)*beta_est^2*t/(2*N^2))
exp(alfa_est*t)
exp(alfa_est*t)-mi
vol*exp(alfa_est*t)
vol*exp(alfa_est*t)-mi
exp((alfa_est-beta_est^2/2)*t)
exp((alfa_est-beta_est^2/2)*t)-mi

```